name: Build Piet Droid APK

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Install Ant
        run: sudo apt-get update && sudo apt-get install -y ant

      - name: Check Project Files
        run: |
          java -version
          javac -version
          ant -version
          ls -R